### ISSUE TITLE
After the installation of PHP, "php -v" still shows 5.3.3

### ISSUE THREAD

**Issue by adriancobb** [JVerstry/openshift-php-framework-stack#2]
When I run php -v, it shows:

PHP 5.3.3 (cli) (built: Jul  3 2015 03:10:33)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with Xdebug v2.1.4, Copyright (c) 2002-2012, by Derick Rethans

what should I do to use PHP 5.6.11 instead? Thanks.

**Comment by JVerstry** [comment]
Sorry for the late reply. Your command returns the default Openshift php version installed in: /usr/bin/php.

That's to be expected, see here for more details: http://stackoverflow.com/questions/31478610/wrong-php-version-returned-in-openshift

**Comment by adriancobb** [comment]
Thanks for the reply. I just noticed this .openshift folder in your project. Thanks!

Date: Sun, 9 Aug 2015 13:18:32 -0700

**Comment by adriancobb** [comment]
Thanks for the reply. I just noticed this .openshift folder in your project. Thanks!
