### ISSUE TITLE
have you tried to install Laravel 5.1 on your PHP stack?

### ISSUE THREAD

**Issue by yizhihou2** [JVerstry/openshift-php-framework-stack#3]
Hi, I tried to install Laravel 5.1 via 
php composer create-project laravel/laravel --prefer-dist

And that's the message I got:

Cannot create cache directory /var/lib/openshift/55fa7b0289f5cf4f86000180/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Installing laravel/laravel (v5.1.11)
Cannot create cache directory /var/lib/openshift/55fa7b0289f5cf4f86000180/.composer/cache/files/, or directory is not writable. Proceeding without cache
  - Installing laravel/laravel (v5.1.11)
    Downloading: 100%

Created project in /var/lib/openshift/55fa7b0289f5cf4f86000180/app-root/runtime/repo/laravel
Cannot create cache directory /var/lib/openshift/55fa7b0289f5cf4f86000180/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/lib/openshift/55fa7b0289f5cf4f86000180/.composer/cache/files/, or directory is not writable. Proceeding without cache
> php -r "copy('.env.example', '.env');"
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php >=5.5.9 but your PHP version (5.3.3) does not satisfy that requirement.
  Problem 2
    - laravel/framework v5.1.9 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.8 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.7 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.6 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.5 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.4 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.3 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.2 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.17 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.16 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.15 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.14 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.13 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.12 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.11 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.10 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.1 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - laravel/framework v5.1.0 requires php >=5.5.9 -> your PHP version (5.3.3) or "config.platform.php" value does not satisfy that requirement.
    - Installation request for laravel/framework 5.1.* -> satisfiable by laravel/framework[v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.12, v5.1.13, v5.1.14, v5.1.15, v5.1.16, v5.1.17, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9].

How to solve this problem? Thanks.

**Comment by JVerstry** [comment]
Did you run php composer after logging into your openshift application/account? If so, then, unfortunately, this command calls the default installation of php on Openshift, which is 5.3.3. I have never used Laravel myself, but would it be possible for you to clone your openshift app locally and run your php composer command locally on your PC? Then commit and push your locally cloned directory? This might be a workaround.

**Comment by yizhihou2** [comment]
Thanks for your suggestion. I just tried to install Laravel locally and push it back to Openshift, but it's not working. I think I will use Laravel 5.0 (supported by Openshift) for now.

Thanks for the help.
